name: Build Pacman Package

on:
  push:
   tags:
    - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #   image: archlinux:base-devel

    steps:
    # - name: Install rust
    #   run: |
    #     pacman -Syu --noconfirm
    #     pacman -Sy git rustup --noconfirm
    #     rustup default stable

    - uses: actions/checkout@v3

    - name: Build Package
      uses: ouuan/pkgbuild-action@master
      id: build-package
      with:
        path: build/PKGBUILD

    - name: Archive pacman package
      uses: actions/upload-artifact@v3
      with:
        name: proxyswarm-x86_64-pacman-package
        path: ${{ steps.build-package.outputs.pkgfile }}
