name: Build Pacman Package

on:
  push:
   tags:
    - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux

    steps:
    - name: Install rust
      run: |
        useradd -m build
        pacman -Syu --noconfirm
        pacman -S base-devel rustup git --noconfirm
        rustup default stable
        echo "build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build

        cd /home/build

    - uses: actions/checkout@v3

    - name: Build pacman package
      run: |
        cd build
        sudo -u build makepkg --noconfirm

    - name: Archive pacman package
      uses: actions/upload-artifact@v3
      with:
        name: proxyswarm-x86_64-pacman-package
        path: build/*.zst
