name: Build and publish

on:
  push:
   tags:
    - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu
            name: linux
            extension: 
            platform: x86_64-unknown-linux-gnu
          - os: windows
            name: win32
            extension: ".exe"
            platform: x86_64-pc-windows-gnu
          - os: macos
            name: macos
            extension: 
            platform: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Archive binary file
      uses: actions/upload-artifact@v3
      with:
        name: proxyswarm-x86_64-${{ matrix.name }}
        path: target/release/proxyswarm${{ matrix.extension }}
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: true
        files: target/release/proxyswarm-${{ matrix.platform }}${{ matrix.extension }}

